macos_instance:
  image: ghcr.io/cirruslabs/macos-runner:tahoe
task:
  required_pr_labels: cirrusci
  skip: "!changesIncludeOnly('Project.toml')"
  name: maOS M1
  env:
    matrix:
      - JULIA_VERSION: 1
  install_script:
    - sh -c "$(curl https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
